Clientside dev
Compro-Single-Step/SIMS-Builder pull request #10
Opened 2017-03-06 11:50 UTC by ashish-compro

Code Review feedback incorporated.

2017-03-06 12:42 UTC, dhirendra-singh81 commented on client/app/shared/input-factory.service.ts
> +    comp.instance["compConfig"] = itemConfig;
Add a setter fn here

2017-03-06 12:55 UTC, dhirendra-singh81 commented on client/app/shared/panel/panel.component.ts
> +    for (let item of this.compConfig.items) {
Put it in a function or maybe we define an interface for a non-leaf component

2017-03-06 13:07 UTC, dhirendra-singh81 requested changes
1. Add non-leaf and derive appropriate component from it 
2. Add a setter fn in input factory service comp

2017-03-07 07:24 UTC, vsingb3 commented on client/app/shared/input-factory.service.ts
> +  public createComp (vCref: ViewContainerRef, itemConfig){
vCRef

2017-03-07 07:26 UTC, vsingb3 commented on client/app/shared/input-factory.service.ts
> +     * [resolveComponentFactory - We create a factory out of the component we want to create]
Get the factory object to create the component

2017-03-08 05:21 UTC, vsingb3 commented on client/app/shared/select/select.component.html
> +<div><app-label [compConfig]="labelConfig"></app-label></div>
Id should be unique for every instance of this component.

Name should be generic

2017-03-16 11:00 UTC, dhirendra-singh81 approved these changes

2017-03-16 11:05 UTC, dhirendra-singh81 requested changes
Unapproving

2017-03-18 11:20 UTC, dhirendra-singh81 approved these changes
Logically reviewed. Code refinements still needed.

2017-03-18 11:20 UTC, merged